#pragma once
#ifndef ENTITYID_H
#define ENTITYID_H

enum
{
	// objects
	EID_PLAYER,
	EID_KITTY,
	EID_SKJUTARN,
	EID_KATTN,
	EID_WOODENBOX,
	EID_BARREL,
	EID_CATFISH,
	EID_DUMMYPLAYER, // map tester
	EID_BOSSTRIGGER,
	EID_ENDMAP,

	EID_MV_PLATFORM_U,
	EID_MV_PLATFORM_D,
	EID_MV_PLATFORM_L,
	EID_MV_PLATFORM_R,

	EID_WOODENBOX_RESPAWN,
	EID_BOSS2TRIGGER,
	EID_COPYCAT,
	EID_PIGGATTACK,
	EID_ONEUP,
	EID_PIGGFACTORY,
	EID_BOSS2DOOR,

	// mostly internal
	EID_LAZERBEAM = 500,
	
	EID_BOSSROCKET,
	EID_BOSSSURPRISE,
	EID_BOSSOBJECT,
	
	EID_BOSS2OBJECT,
	EID_BOSS2FIREBALL,
	EID_BOSS2GRNDFIRE,
	EID_BOSS2SHIELD,
	EID_BOSS2SEQUENCER
};

#endif // ENTITYID_H
